import "dotenv/config";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/prisma/client";

const connectionString = `${process.env.DATABASE_URL}`;
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function testConnection() {
  try {
    const client = await pool.connect();
    client.release();
    console.log("Connected to PostgreSQL successfully!");
    return true;
  } catch (error) {
    console.error("Failed to connect to PostgreSQL:", error);
    return false;
  }
}

async function main() {
  console.log("Starting seeding...");
  console.log("Checking connection...");
  const isConnected = await testConnection();
  if (!isConnected) {
    throw new Error("Not connected!");
  }
  console.log("Cleaning existing data...");
  // Сначала удаляем зависимые таблицы (junction), потом основные
  await prisma.userCanTeach.deleteMany();
  await prisma.userWantsToLearn.deleteMany();
  await prisma.user.deleteMany();
  await prisma.subskills.deleteMany();
  await prisma.skills.deleteMany();
  await prisma.cities.deleteMany();
  await prisma.genders.deleteMany();
  console.log("Creating cities data...");
  await prisma.cities.createMany({
    data: [
      {
        id: 1,
        title: "Москва",
      },
      {
        id: 2,
        title: "Санкт-Петербург",
      },
      {
        id: 3,
        title: "Новосибирск",
      },
      {
        id: 4,
        title: "Екатеринбург",
      },
      {
        id: 5,
        title: "Казань",
      },
      {
        id: 6,
        title: "Мурманск",
      },
      {
        id: 7,
        title: "Владивосток",
      },
      {
        id: 8,
        title: "Иркутск",
      },
      {
        id: 9,
        title: "Тула",
      },
      {
        id: 10,
        title: "Тверь",
      },
      {
        id: 11,
        title: "Воронеж",
      },
      {
        id: 12,
        title: "Махачкала",
      },
    ],
  });
  console.log("Creating genders data...");
  await prisma.genders.createMany({
    data: [
      {
        id: 1,
        title: "male",
      },
      {
        id: 2,
        title: "female",
      },
      {
        id: 3,
        title: "irrelevant",
      },
    ],
  });
  console.log("Creating skills data...");
  await prisma.skills.createMany({
    data: [
      {
        id: 1,
        title: "Бизнес и карьера",
        color: "light_lavender",
        icon_src: "/assets/skills/BusinessAndCareerIcon.svg",
      },
      {
        id: 2,
        title: "Творчество и искусство",
        color: "light_pink",
        icon_src: "/assets/skills/CreativityIcon.svg",
      },
      {
        id: 3,
        title: "Образование и развитие",
        color: "pale_blue",
        icon_src: "/assets/skills/EducationIcon.svg",
      },
      {
        id: 4,
        title: "Иностранные языки",
        color: "light_beige",
        icon_src: "/assets/skills/ForeignLanguagesIcon.svg",
      },
      {
        id: 5,
        title: "Здоровье и лайфстайл",
        color: "pale_green",
        icon_src: "/assets/skills/HealthIcon.svg",
      },
      {
        id: 6,
        title: "Дом и уют",
        color: "light_peach",
        icon_src: "/assets/skills/HouseIcon.svg",
      },
    ],
  });
  console.log("Creating subskills data...");
  await prisma.subskills.createMany({
    data: [
      {
        id: 1,
        title: "Управление командой",
        skill_id: 1,
      },
      {
        id: 2,
        title: "Маркетинг и реклама",
        skill_id: 1,
      },
      {
        id: 3,
        title: "Продажи и переговоры",
        skill_id: 1,
      },
      {
        id: 4,
        title: "Личный бренд",
        skill_id: 1,
      },
      {
        id: 5,
        title: "Резюме и собеседование",
        skill_id: 1,
      },
      {
        id: 6,
        title: "Тайм-менеджмент",
        skill_id: 1,
      },
      {
        id: 7,
        title: "Проектное управление",
        skill_id: 1,
      },
      {
        id: 8,
        title: "Предпринимательство",
        skill_id: 1,
      },
      {
        id: 9,
        title: "Рисование и иллюстрация",
        skill_id: 2,
      },
      {
        id: 10,
        title: "Фотография",
        skill_id: 2,
      },
      {
        id: 11,
        title: "Видеомонтаж",
        skill_id: 2,
      },
      {
        id: 12,
        title: "Музыка и звук",
        skill_id: 2,
      },
      {
        id: 13,
        title: "Актерское мастерство",
        skill_id: 2,
      },
      {
        id: 14,
        title: "Креативное письмо",
        skill_id: 2,
      },
      {
        id: 15,
        title: "Арт-терапия",
        skill_id: 2,
      },
      {
        id: 16,
        title: "Декор и DIY",
        skill_id: 2,
      },
      {
        id: 17,
        title: "Личностное развитие",
        skill_id: 3,
      },
      {
        id: 18,
        title: "Навыки обучения",
        skill_id: 3,
      },
      {
        id: 19,
        title: "Когнитивные техники",
        skill_id: 3,
      },
      {
        id: 20,
        title: "Скорочтение",
        skill_id: 3,
      },
      {
        id: 21,
        title: "Навыки преподавания",
        skill_id: 3,
      },
      {
        id: 22,
        title: "Коучинг",
        skill_id: 3,
      },
      {
        id: 23,
        title: "Английский",
        skill_id: 4,
      },
      {
        id: 24,
        title: "Французский",
        skill_id: 4,
      },
      {
        id: 25,
        title: "Испанский",
        skill_id: 4,
      },
      {
        id: 26,
        title: "Немецкий",
        skill_id: 4,
      },
      {
        id: 27,
        title: "Китайский",
        skill_id: 4,
      },
      {
        id: 28,
        title: "Японский",
        skill_id: 4,
      },
      {
        id: 29,
        title: "Подготовка к экзаменам (IELTS, TOEFL)",
        skill_id: 4,
      },
      {
        id: 30,
        title: "Йога и медитация",
        skill_id: 5,
      },
      {
        id: 31,
        title: "Питание и ЗОЖ",
        skill_id: 5,
      },
      {
        id: 32,
        title: "Ментальное здоровье",
        skill_id: 5,
      },
      {
        id: 33,
        title: "Осознанность",
        skill_id: 5,
      },
      {
        id: 34,
        title: "Физические тренировки",
        skill_id: 5,
      },
      {
        id: 35,
        title: "Сон и восстановление",
        skill_id: 5,
      },
      {
        id: 36,
        title: "Баланс жизни и работы",
        skill_id: 5,
      },
      {
        id: 37,
        title: "Уборка и организация",
        skill_id: 6,
      },
      {
        id: 38,
        title: "Домашние финансы",
        skill_id: 6,
      },
      {
        id: 39,
        title: "Приготовление еды",
        skill_id: 6,
      },
      {
        id: 40,
        title: "Домашние растения",
        skill_id: 6,
      },
      {
        id: 41,
        title: "Ремонт",
        skill_id: 6,
      },
      {
        id: 42,
        title: "Хранение вещей",
        skill_id: 6,
      },
    ],
  });
  console.log("Creating user data...");
  await prisma.user.createMany({
    data: [
      {
        id: 1,
        bio: "Люблю ритм, музыку и живые выступления. Учу играть на барабанах.",
        email: "ivan@mail.ru",
        password: "12345",
        name: "Иван",
        image_path: "avatar-1.jpg",
        gender_id: 1,
        birth_date: new Date("1995-04-10"),
        city_id: 1,
        likes_count: 12,
        creation_date: new Date("2024-01-15T10:00:00"),
        refreshToken: "",
      },
      {
        id: 2,
        bio: "Преподаю английский и помогаю преодолеть языковой барьер.",
        email: "maria@mail.ru",
        password: "12345",
        name: "Мария",
        image_path: "avatar-2.jpg",
        gender_id: 2,
        birth_date: new Date("1998-07-22"),
        city_id: 2,
        likes_count: 25,
        creation_date: new Date("2024-02-03T14:30:00"),
        refreshToken: "",
      },
      {
        id: 3,
        bio: "Развиваю личный бренд и помогаю другим выстраивать карьеру.",
        email: "alexey@mail.ru",
        password: "12345",
        name: "Алексей",
        image_path: "avatar-3.jpg",
        gender_id: 1,
        birth_date: new Date("1993-11-05"),
        city_id: 1,
        likes_count: 18,
        creation_date: new Date("2024-02-20T09:15:00"),
        refreshToken: "",
      },
      {
        id: 4,
        bio: "Учу английский с нуля и готовлю к международным экзаменам.",
        email: "elena@mail.ru",
        password: "12345",
        name: "Елена",
        image_path: "avatar-4.jpg",
        gender_id: 2,
        birth_date: new Date("1997-01-18"),
        city_id: 3,
        likes_count: 14,
        creation_date: new Date("2024-03-08T16:45:00"),
        refreshToken: "",
      },
      {
        id: 5,
        bio: "Разговорный английский, сленг и уверенность в общении.",
        email: "dmitry@mail.ru",
        password: "12345",
        name: "Дмитрий",
        image_path: "avatar-5.jpg",
        gender_id: 1,
        birth_date: new Date("1996-09-30"),
        city_id: 4,
        likes_count: 9,
        creation_date: new Date("2024-03-25T11:20:00"),
        refreshToken: "",
      },
      {
        id: 6,
        bio: "Гитара, акустика и немного теории музыки для начинающих.",
        email: "olga@mail.ru",
        password: "12345",
        name: "Ольга",
        image_path: "avatar-6.jpg",
        gender_id: 2,
        birth_date: new Date("2000-05-12"),
        city_id: 2,
        likes_count: 21,
        creation_date: new Date("2024-04-12T13:00:00"),
        refreshToken: "",
      },
      {
        id: 7,
        bio: "Фотография как способ видеть мир по-новому. Учу снимать на телефон и зеркалку.",
        email: "sergey@mail.ru",
        password: "12345",
        name: "Сергей",
        image_path: "avatar-7.jpg",
        gender_id: 1,
        birth_date: new Date("1994-12-03"),
        city_id: 5,
        likes_count: 16,
        creation_date: new Date("2024-04-28T17:40:00"),
        refreshToken: "",
      },
      {
        id: 8,
        bio: "Готовлю просто и вкусно. Делюсь базовыми техниками и любимыми рецептами.",
        email: "anna@mail.ru",
        password: "12345",
        name: "Анна",
        image_path: "avatar-8.jpg",
        gender_id: 2,
        birth_date: new Date("1999-08-14"),
        city_id: 1,
        likes_count: 11,
        creation_date: new Date("2024-05-15T08:55:00"),
        refreshToken: "",
      },
      {
        id: 9,
        bio: "Программирую на Python и JavaScript. Помогаю разобраться с основами.",
        email: "pavel@mail.ru",
        password: "12345",
        name: "Павел",
        image_path: "avatar-9.jpg",
        gender_id: 1,
        birth_date: new Date("1997-06-27"),
        city_id: 3,
        likes_count: 7,
        creation_date: new Date("2024-06-01T12:10:00"),
        refreshToken: "",
      },
      {
        id: 10,
        bio: "Испанский язык с нуля до уверенного разговора.",
        email: "natalia@mail.ru",
        password: "12345",
        name: "Наталья",
        image_path: "avatar-10.jpg",
        gender_id: 2,
        birth_date: new Date("2001-02-19"),
        city_id: 6,
        likes_count: 19,
        creation_date: new Date("2024-06-18T15:25:00"),
        refreshToken: "",
      },
      {
        id: 11,
        bio: "Шахматы для начинающих и продолжающих. Тактика и стратегия.",
        email: "andrey@mail.ru",
        password: "12345",
        name: "Андрей",
        image_path: "avatar-11.png",
        gender_id: 1,
        birth_date: new Date("1992-10-08"),
        city_id: 4,
        likes_count: 13,
        creation_date: new Date("2024-07-05T09:40:00"),
        refreshToken: "",
      },
      {
        id: 12,
        bio: "Рисую акварелью и маркерами. Учу видеть цвет и форму.",
        email: "sofia@mail.ru",
        password: "12345",
        name: "София",
        image_path: "avatar-12.jpg",
        gender_id: 2,
        birth_date: new Date("2002-03-21"),
        city_id: 7,
        likes_count: 22,
        creation_date: new Date("2024-07-22T14:15:00"),
        refreshToken: "",
      },
      {
        id: 13,
        bio: "Йога для тела и ума. Мягкие практики для любого уровня.",
        email: "mikhail@mail.ru",
        password: "12345",
        name: "Михаил",
        image_path: "avatar-13.jpg",
        gender_id: 1,
        birth_date: new Date("1995-07-16"),
        city_id: 1,
        likes_count: 8,
        creation_date: new Date("2024-08-08T11:50:00"),
        refreshToken: "",
      },
      {
        id: 14,
        bio: "Вокал и постановка голоса. Помогаю зазвучать уверенно.",
        email: "ekaterina@mail.ru",
        password: "12345",
        name: "Екатерина",
        image_path: "avatar-14.jpg",
        gender_id: 2,
        birth_date: new Date("1998-11-29"),
        city_id: 2,
        likes_count: 15,
        creation_date: new Date("2024-08-25T16:05:00"),
        refreshToken: "",
      },
      {
        id: 15,
        bio: "Монтаж видео в Premiere и CapCut. От идеи до готового ролика.",
        email: "nikita@mail.ru",
        password: "12345",
        name: "Никита",
        image_path: "avatar-15.jpg",
        gender_id: 1,
        birth_date: new Date("2000-01-04"),
        city_id: 5,
        likes_count: 10,
        creation_date: new Date("2024-09-10T10:30:00"),
        refreshToken: "",
      },
      {
        id: 16,
        bio: "Немецкий язык: грамматика, разговор и культура.",
        email: "irina2@mail.ru",
        password: "12345",
        name: "Ирина",
        image_path: "avatar-16.png",
        gender_id: 2,
        birth_date: new Date("1996-04-17"),
        city_id: 3,
        likes_count: 17,
        creation_date: new Date("2024-09-27T13:45:00"),
        refreshToken: "",
      },
      {
        id: 17,
        bio: "Веб-дизайн: Figma, композиция и понятные интерфейсы.",
        email: "roman@mail.ru",
        password: "12345",
        name: "Роман",
        image_path: "avatar-17.jpg",
        gender_id: 1,
        birth_date: new Date("1999-09-09"),
        city_id: 6,
        likes_count: 6,
        creation_date: new Date("2024-10-14T08:20:00"),
        refreshToken: "",
      },
      {
        id: 18,
        bio: "Плавание и техника дыхания. Тренировки для любого возраста.",
        email: "daria@mail.ru",
        password: "12345",
        name: "Дарья",
        image_path: "avatar-18.jpg",
        gender_id: 2,
        birth_date: new Date("2001-12-25"),
        city_id: 4,
        likes_count: 20,
        creation_date: new Date("2024-10-30T15:55:00"),
        refreshToken: "",
      },
      {
        id: 19,
        bio: "Маркетинг и реклама: как доносить ценность продукта.",
        email: "maxim@mail.ru",
        password: "12345",
        name: "Максим",
        image_path: "avatar-19.jpg",
        gender_id: 1,
        birth_date: new Date("1994-05-31"),
        city_id: 7,
        likes_count: 14,
        creation_date: new Date("2024-11-16T12:40:00"),
        refreshToken: "",
      },
      {
        id: 20,
        bio: "Каллиграфия и красивый почерк. От основ до своих шрифтов.",
        email: "alina@mail.ru",
        password: "12345",
        name: "Алина",
        image_path: "avatar-20.jpg",
        gender_id: 2,
        birth_date: new Date("1997-08-07"),
        city_id: 1,
        likes_count: 23,
        creation_date: new Date("2024-12-02T09:10:00"),
        refreshToken: "",
      },
      // Пользователи 21–100
      {
        id: 21,
        bio: "Люблю фотографировать город и искать необычное в обычных местах.",
        email: "artem@mail.ru",
        password: "12345",
        name: "Артём",
        image_path: "avatar-21.jpg",
        gender_id: 1,
        birth_date: new Date("1998-03-12"),
        city_id: 3,
        likes_count: 6,
        creation_date: new Date("2024-08-21T11:24:00"),
        refreshToken: "",
      },
      {
        id: 22,
        bio: "Изучаю французский и мечтаю однажды свободно говорить без переводчика.",
        email: "polina@mail.ru",
        password: "12345",
        name: "Полина",
        image_path: "avatar-22.jpg",
        gender_id: 2,
        birth_date: new Date("2001-09-27"),
        city_id: 2,
        likes_count: 15,
        creation_date: new Date("2024-09-03T15:42:00"),
        refreshToken: "",
      },
      {
        id: 23,
        bio: "Разбираюсь в финансах и учусь объяснять сложные вещи простыми словами.",
        email: "kirill@mail.ru",
        password: "12345",
        name: "Кирилл",
        image_path: "avatar-23.jpg",
        gender_id: 1,
        birth_date: new Date("1997-12-04"),
        city_id: 5,
        likes_count: 9,
        creation_date: new Date("2024-09-18T09:15:00"),
        refreshToken: "",
      },
      {
        id: 24,
        bio: "Путешествия, книги и новые языки — три вещи, без которых я не представляю жизнь.",
        email: "veronika@mail.ru",
        password: "12345",
        name: "Вероника",
        image_path: "avatar-24.jpg",
        gender_id: 2,
        birth_date: new Date("2000-04-19"),
        city_id: 6,
        likes_count: 18,
        creation_date: new Date("2024-10-02T12:37:00"),
        refreshToken: "",
      },
      {
        id: 25,
        bio: "Учусь готовить азиатские блюда и постоянно экспериментирую с рецептами.",
        email: "timur@mail.ru",
        password: "12345",
        name: "Тимур",
        image_path: "avatar-25.jpg",
        gender_id: 1,
        birth_date: new Date("2003-06-08"),
        city_id: 1,
        likes_count: 4,
        creation_date: new Date("2024-10-19T18:21:00"),
        refreshToken: "",
      },
      {
        id: 26,
        bio: "Люблю танцы, музыку и людей, которые умеют смеяться над собой.",
        email: "ksenia@mail.ru",
        password: "12345",
        name: "Ксения",
        image_path: "avatar-26.jpg",
        gender_id: 2,
        birth_date: new Date("1999-01-26"),
        city_id: 4,
        likes_count: 22,
        creation_date: new Date("2024-11-05T10:18:00"),
        refreshToken: "",
      },
      {
        id: 27,
        bio: "Программирую днём, читаю вечером. Постоянно пытаюсь найти баланс.",
        email: "roman2@mail.ru",
        password: "12345",
        name: "Роман",
        image_path: "avatar-27.jpg",
        gender_id: 1,
        birth_date: new Date("2002-11-14"),
        city_id: 7,
        likes_count: 8,
        creation_date: new Date("2024-11-22T14:53:00"),
        refreshToken: "",
      },
      {
        id: 28,
        bio: "Изучаю психологию и учусь лучше понимать себя и окружающих.",
        email: "yulia@mail.ru",
        password: "12345",
        name: "Юлия",
        image_path: "avatar-28.jpg",
        gender_id: 2,
        birth_date: new Date("1996-08-17"),
        city_id: 3,
        likes_count: 13,
        creation_date: new Date("2024-12-07T16:29:00"),
        refreshToken: "",
      },
      {
        id: 29,
        bio: "Могу часами говорить о кино, музыке и хороших историях.",
        email: "denis@mail.ru",
        password: "12345",
        name: "Денис",
        image_path: "avatar-29.jpg",
        gender_id: 1,
        birth_date: new Date("1995-05-22"),
        city_id: 2,
        likes_count: 11,
        creation_date: new Date("2024-12-19T08:47:00"),
        refreshToken: "",
      },
      {
        id: 30,
        bio: "Учу рисовать и сама постоянно учусь у других художников.",
        email: "nastya@mail.ru",
        password: "12345",
        name: "Анастасия",
        image_path: "avatar-30.jpg",
        gender_id: 2,
        birth_date: new Date("2004-02-03"),
        city_id: 5,
        likes_count: 7,
        creation_date: new Date("2025-01-06T13:12:00"),
        refreshToken: "",
      },
      {
        id: 31,
        bio: "Люблю спорт, бег и длинные прогулки. Всегда ищу новые цели.",
        email: "vlad@mail.ru",
        password: "12345",
        name: "Владислав",
        image_path: "avatar-31.jpg",
        gender_id: 1,
        birth_date: new Date("1999-07-29"),
        city_id: 6,
        likes_count: 16,
        creation_date: new Date("2025-01-18T17:35:00"),
        refreshToken: "",
      },
      {
        id: 32,
        bio: "Мечтаю научиться играть на пианино и не бояться выступать перед людьми.",
        email: "diana@mail.ru",
        password: "12345",
        name: "Диана",
        image_path: "avatar-32.jpg",
        gender_id: 2,
        birth_date: new Date("2002-10-11"),
        city_id: 1,
        likes_count: 5,
        creation_date: new Date("2025-02-02T11:08:00"),
        refreshToken: "",
      },
      {
        id: 33,
        bio: "Люблю мастерить вещи своими руками и разбираться, как всё устроено.",
        email: "igor@mail.ru",
        password: "12345",
        name: "Игорь",
        image_path: "avatar-33.jpg",
        gender_id: 1,
        birth_date: new Date("1994-09-06"),
        city_id: 4,
        likes_count: 12,
        creation_date: new Date("2025-02-17T09:41:00"),
        refreshToken: "",
      },
      {
        id: 34,
        bio: "Изучаю дизайн и собираю портфолио из маленьких проектов.",
        email: "liza@mail.ru",
        password: "12345",
        name: "Елизавета",
        image_path: "avatar-34.jpg",
        gender_id: 2,
        birth_date: new Date("2001-12-20"),
        city_id: 7,
        likes_count: 19,
        creation_date: new Date("2025-03-04T15:16:00"),
        refreshToken: "",
      },
      {
        id: 35,
        bio: "Люблю походы, природу и разговоры у костра.",
        email: "nikolay@mail.ru",
        password: "12345",
        name: "Николай",
        image_path: "avatar-35.jpg",
        gender_id: 1,
        birth_date: new Date("1998-06-15"),
        city_id: 3,
        likes_count: 10,
        creation_date: new Date("2025-03-21T12:54:00"),
        refreshToken: "",
      },
      {
        id: 36,
        bio: "Учу итальянский, готовлю пасту и пытаюсь не превращать кухню в экспериментальную лабораторию.",
        email: "aleksandra@mail.ru",
        password: "12345",
        name: "Александра",
        image_path: "avatar-36.jpg",
        gender_id: 2,
        birth_date: new Date("1997-03-28"),
        city_id: 5,
        likes_count: 14,
        creation_date: new Date("2025-04-08T18:03:00"),
        refreshToken: "",
      },
      {
        id: 37,
        bio: "Развиваюсь в аналитике и люблю находить закономерности там, где другие видят хаос.",
        email: "evgeny@mail.ru",
        password: "12345",
        name: "Евгений",
        image_path: "avatar-37.jpg",
        gender_id: 1,
        birth_date: new Date("1996-11-09"),
        city_id: 2,
        likes_count: 20,
        creation_date: new Date("2025-04-24T10:27:00"),
        refreshToken: "",
      },
      {
        id: 38,
        bio: "Фотографирую людей и моменты, которые хочется сохранить.",
        email: "irina@mail.ru",
        password: "12345",
        name: "Ирина",
        image_path: "avatar-38.jpg",
        gender_id: 2,
        birth_date: new Date("1998-01-31"),
        city_id: 6,
        likes_count: 17,
        creation_date: new Date("2025-05-11T14:39:00"),
        refreshToken: "",
      },
      {
        id: 39,
        bio: "Люблю шахматы, стратегию и задачи, над которыми приходится подумать.",
        email: "oleg@mail.ru",
        password: "12345",
        name: "Олег",
        image_path: "avatar-39.jpg",
        gender_id: 1,
        birth_date: new Date("1993-05-17"),
        city_id: 1,
        likes_count: 9,
        creation_date: new Date("2025-05-27T16:52:00"),
        refreshToken: "",
      },
      {
        id: 40,
        bio: "Мечтаю писать книги и каждый день стараюсь написать хотя бы пару страниц.",
        email: "tatiana@mail.ru",
        password: "12345",
        name: "Татьяна",
        image_path: "avatar-40.jpg",
        gender_id: 2,
        birth_date: new Date("1995-10-24"),
        city_id: 4,
        likes_count: 23,
        creation_date: new Date("2025-06-13T09:34:00"),
        refreshToken: "",
      },
      {
        id: 41,
        bio: "Изучаю веб-разработку и постепенно превращаю идеи в работающие проекты.",
        email: "stepan@mail.ru",
        password: "12345",
        name: "Степан",
        image_path: "avatar-41.jpg",
        gender_id: 1,
        birth_date: new Date("2003-04-07"),
        city_id: 7,
        likes_count: 6,
        creation_date: new Date("2025-06-29T11:47:00"),
        refreshToken: "",
      },
      {
        id: 42,
        bio: "Люблю цветы, растения и всё, что помогает сделать дом уютнее.",
        email: "marina@mail.ru",
        password: "12345",
        name: "Марина",
        image_path: "avatar-42.jpg",
        gender_id: 2,
        birth_date: new Date("1999-09-13"),
        city_id: 3,
        likes_count: 15,
        creation_date: new Date("2025-07-15T13:25:00"),
        refreshToken: "",
      },
      {
        id: 43,
        bio: "Увлекаюсь автомобилями и могу часами рассказывать о технике.",
        email: "anton@mail.ru",
        password: "12345",
        name: "Антон",
        image_path: "avatar-43.jpg",
        gender_id: 1,
        birth_date: new Date("1997-07-02"),
        city_id: 5,
        likes_count: 18,
        creation_date: new Date("2025-08-01T19:18:00"),
        refreshToken: "",
      },
      {
        id: 44,
        bio: "Учу корейский и интересуюсь современной культурой Южной Кореи.",
        email: "vera@mail.ru",
        password: "12345",
        name: "Вера",
        image_path: "avatar-44.jpg",
        gender_id: 2,
        birth_date: new Date("2002-01-18"),
        city_id: 2,
        likes_count: 21,
        creation_date: new Date("2025-08-18T08:36:00"),
        refreshToken: "",
      },
      {
        id: 45,
        bio: "Бегаю, читаю и учусь не откладывать важные дела на завтра.",
        email: "matvey@mail.ru",
        password: "12345",
        name: "Матвей",
        image_path: "avatar-45.jpg",
        gender_id: 1,
        birth_date: new Date("2000-12-02"),
        city_id: 6,
        likes_count: 8,
        creation_date: new Date("2025-09-03T15:11:00"),
        refreshToken: "",
      },
      {
        id: 46,
        bio: "Люблю музыку, концерты и длинные прогулки по вечернему городу.",
        email: "ekaterina2@mail.ru",
        password: "12345",
        name: "Екатерина",
        image_path: "avatar-46.jpg",
        gender_id: 2,
        birth_date: new Date("1996-06-21"),
        city_id: 1,
        likes_count: 16,
        creation_date: new Date("2025-09-20T17:44:00"),
        refreshToken: "",
      },
      {
        id: 47,
        bio: "Изучаю маркетинг и люблю проверять идеи не только словами, но и цифрами.",
        email: "denis2@mail.ru",
        password: "12345",
        name: "Денис",
        image_path: "avatar-47.jpg",
        gender_id: 1,
        birth_date: new Date("1998-10-30"),
        city_id: 4,
        likes_count: 13,
        creation_date: new Date("2025-10-06T12:19:00"),
        refreshToken: "",
      },
      {
        id: 48,
        bio: "Учу испанский и мечтаю однажды пожить у моря.",
        email: "svetlana@mail.ru",
        password: "12345",
        name: "Светлана",
        image_path: "avatar-48.jpg",
        gender_id: 2,
        birth_date: new Date("2001-05-09"),
        city_id: 7,
        likes_count: 24,
        creation_date: new Date("2025-10-22T10:52:00"),
        refreshToken: "",
      },
      {
        id: 49,
        bio: "Люблю настольные игры и легко соглашаюсь на спонтанные приключения.",
        email: "sergey2@mail.ru",
        password: "12345",
        name: "Сергей",
        image_path: "avatar-49.jpg",
        gender_id: 1,
        birth_date: new Date("1995-02-26"),
        city_id: 3,
        likes_count: 7,
        creation_date: new Date("2025-11-09T14:28:00"),
        refreshToken: "",
      },
      {
        id: 50,
        bio: "Занимаюсь вокалом и учусь уверенно чувствовать себя на сцене.",
        email: "lyudmila@mail.ru",
        password: "12345",
        name: "Людмила",
        image_path: "avatar-50.jpg",
        gender_id: 2,
        birth_date: new Date("1994-07-16"),
        city_id: 5,
        likes_count: 11,
        creation_date: new Date("2025-11-26T18:41:00"),
        refreshToken: "",
      },
      {
        id: 51,
        bio: "Люблю путешествовать налегке и находить интересные места без туристических маршрутов.",
        email: "artem2@mail.ru",
        password: "12345",
        name: "Артём",
        image_path: "avatar-51.jpg",
        gender_id: 1,
        birth_date: new Date("2000-03-03"),
        city_id: 2,
        likes_count: 19,
        creation_date: new Date("2025-12-12T09:16:00"),
        refreshToken: "",
      },
      {
        id: 52,
        bio: "Рисую иллюстрации и постепенно учусь работать с анимацией.",
        email: "oksana@mail.ru",
        password: "12345",
        name: "Оксана",
        image_path: "avatar-52.jpg",
        gender_id: 2,
        birth_date: new Date("1998-12-11"),
        city_id: 6,
        likes_count: 12,
        creation_date: new Date("2025-12-28T13:37:00"),
        refreshToken: "",
      },
      {
        id: 53,
        bio: "Интересуюсь историей, архитектурой и старыми городами.",
        email: "viktor@mail.ru",
        password: "12345",
        name: "Виктор",
        image_path: "avatar-53.jpg",
        gender_id: 1,
        birth_date: new Date("1992-04-25"),
        city_id: 1,
        likes_count: 10,
        creation_date: new Date("2026-01-14T16:05:00"),
        refreshToken: "",
      },
      {
        id: 54,
        bio: "Учу японский и собираю коллекцию любимых слов на разных языках.",
        email: "elizaveta2@mail.ru",
        password: "12345",
        name: "Елизавета",
        image_path: "avatar-54.jpg",
        gender_id: 2,
        birth_date: new Date("2003-08-22"),
        city_id: 4,
        likes_count: 27,
        creation_date: new Date("2026-01-31T11:43:00"),
        refreshToken: "",
      },
      {
        id: 55,
        bio: "Фанат велосипедов, природы и длинных маршрутов за городом.",
        email: "georgy@mail.ru",
        password: "12345",
        name: "Георгий",
        image_path: "avatar-55.jpg",
        gender_id: 1,
        birth_date: new Date("1997-01-06"),
        city_id: 7,
        likes_count: 14,
        creation_date: new Date("2026-02-16T15:27:00"),
        refreshToken: "",
      },
      {
        id: 56,
        bio: "Люблю выпечку, уютные кафе и хорошие разговоры.",
        email: "valeria@mail.ru",
        password: "12345",
        name: "Валерия",
        image_path: "avatar-56.jpg",
        gender_id: 2,
        birth_date: new Date("2000-06-13"),
        city_id: 3,
        likes_count: 20,
        creation_date: new Date("2026-03-03T10:14:00"),
        refreshToken: "",
      },
      {
        id: 57,
        bio: "Работаю с данными и учусь превращать таблицы в понятные истории.",
        email: "ilya@mail.ru",
        password: "12345",
        name: "Илья",
        image_path: "avatar-57.jpg",
        gender_id: 1,
        birth_date: new Date("1999-11-28"),
        city_id: 5,
        likes_count: 5,
        creation_date: new Date("2026-03-19T12:48:00"),
        refreshToken: "",
      },
      {
        id: 58,
        bio: "Учу английский через фильмы, сериалы и живое общение.",
        email: "alena@mail.ru",
        password: "12345",
        name: "Алёна",
        image_path: "avatar-58.jpg",
        gender_id: 2,
        birth_date: new Date("2004-09-05"),
        city_id: 2,
        likes_count: 18,
        creation_date: new Date("2026-04-04T17:22:00"),
        refreshToken: "",
      },
      {
        id: 59,
        bio: "Занимаюсь фотографией и иногда снимаю небольшие документальные истории.",
        email: "vadim@mail.ru",
        password: "12345",
        name: "Вадим",
        image_path: "avatar-59.jpg",
        gender_id: 1,
        birth_date: new Date("1996-03-19"),
        city_id: 6,
        likes_count: 9,
        creation_date: new Date("2026-04-21T08:57:00"),
        refreshToken: "",
      },
      {
        id: 60,
        bio: "Изучаю UX и хочу создавать интерфейсы, которыми приятно пользоваться.",
        email: "arina@mail.ru",
        password: "12345",
        name: "Арина",
        image_path: "avatar-60.jpg",
        gender_id: 2,
        birth_date: new Date("2002-02-14"),
        city_id: 1,
        likes_count: 25,
        creation_date: new Date("2026-05-07T14:31:00"),
        refreshToken: "",
      },
      {
        id: 61,
        bio: "Люблю бегать по утрам и ставить себе небольшие, но реальные цели.",
        email: "ruslan@mail.ru",
        password: "12345",
        name: "Руслан",
        image_path: "avatar-61.jpg",
        gender_id: 1,
        birth_date: new Date("1995-08-08"),
        city_id: 4,
        likes_count: 13,
        creation_date: new Date("2026-05-24T09:42:00"),
        refreshToken: "",
      },
      {
        id: 62,
        bio: "Играю на укулеле, пою и собираю плейлисты под любое настроение.",
        email: "karina@mail.ru",
        password: "12345",
        name: "Карина",
        image_path: "avatar-62.jpg",
        gender_id: 2,
        birth_date: new Date("2001-11-17"),
        city_id: 7,
        likes_count: 16,
        creation_date: new Date("2026-06-09T16:18:00"),
        refreshToken: "",
      },
      {
        id: 63,
        bio: "Интересуюсь искусственным интеллектом и современными технологиями.",
        email: "nikolay2@mail.ru",
        password: "12345",
        name: "Николай",
        image_path: "avatar-63.jpg",
        gender_id: 1,
        birth_date: new Date("1998-05-03"),
        city_id: 3,
        likes_count: 21,
        creation_date: new Date("2026-06-25T11:36:00"),
        refreshToken: "",
      },
      {
        id: 64,
        bio: "Люблю йогу, книги и тихие вечера без телефона.",
        email: "ekaterina3@mail.ru",
        password: "12345",
        name: "Екатерина",
        image_path: "avatar-64.jpg",
        gender_id: 2,
        birth_date: new Date("1997-10-29"),
        city_id: 5,
        likes_count: 8,
        creation_date: new Date("2026-07-11T13:49:00"),
        refreshToken: "",
      },
      {
        id: 65,
        bio: "Разрабатываю приложения и постоянно ищу новые способы сделать код проще.",
        email: "mikhail2@mail.ru",
        password: "12345",
        name: "Михаил",
        image_path: "avatar-65.jpg",
        gender_id: 1,
        birth_date: new Date("1999-02-12"),
        city_id: 2,
        likes_count: 17,
        creation_date: new Date("2026-07-27T18:26:00"),
        refreshToken: "",
      },
      {
        id: 66,
        bio: "Пишу стихи, фотографирую закаты и учусь замечать маленькие детали.",
        email: "sofia2@mail.ru",
        password: "12345",
        name: "София",
        image_path: "avatar-66.jpg",
        gender_id: 2,
        birth_date: new Date("2005-04-23"),
        city_id: 6,
        likes_count: 22,
        creation_date: new Date("2026-08-13T10:07:00"),
        refreshToken: "",
      },
      {
        id: 67,
        bio: "Люблю готовить и собирать друзей за большим столом.",
        email: "danil@mail.ru",
        password: "12345",
        name: "Данил",
        image_path: "avatar-67.jpg",
        gender_id: 1,
        birth_date: new Date("2000-07-05"),
        city_id: 1,
        likes_count: 11,
        creation_date: new Date("2026-08-29T15:33:00"),
        refreshToken: "",
      },
      {
        id: 68,
        bio: "Изучаю немецкий и мечтаю однажды пожить в Берлине.",
        email: "elena2@mail.ru",
        password: "12345",
        name: "Елена",
        image_path: "avatar-68.jpg",
        gender_id: 2,
        birth_date: new Date("1996-12-19"),
        city_id: 4,
        likes_count: 19,
        creation_date: new Date("2026-09-14T12:45:00"),
        refreshToken: "",
      },
      {
        id: 69,
        bio: "Занимаюсь музыкой и учусь создавать электронные треки.",
        email: "nikita2@mail.ru",
        password: "12345",
        name: "Никита",
        image_path: "avatar-69.jpg",
        gender_id: 1,
        birth_date: new Date("2003-01-27"),
        city_id: 7,
        likes_count: 7,
        creation_date: new Date("2026-09-30T09:21:00"),
        refreshToken: "",
      },
      {
        id: 70,
        bio: "Люблю путешествия, новые знакомства и истории людей.",
        email: "maria2@mail.ru",
        password: "12345",
        name: "Мария",
        image_path: "avatar-70.jpg",
        gender_id: 2,
        birth_date: new Date("1999-06-07"),
        city_id: 3,
        likes_count: 28,
        creation_date: new Date("2026-10-01T16:54:00"),
        refreshToken: "",
      },
      {
        id: 71,
        bio: "Учу программирование и стараюсь каждый день писать хотя бы немного кода.",
        email: "alexander@mail.ru",
        password: "12345",
        name: "Александр",
        image_path: "avatar-71.jpg",
        gender_id: 1,
        birth_date: new Date("2001-03-16"),
        city_id: 5,
        likes_count: 12,
        creation_date: new Date("2026-10-02T10:18:00"),
        refreshToken: "",
      },
      {
        id: 72,
        bio: "Рисую, читаю и изучаю историю искусства.",
        email: "sofia3@mail.ru",
        password: "12345",
        name: "София",
        image_path: "avatar-72.jpg",
        gender_id: 2,
        birth_date: new Date("2004-11-09"),
        city_id: 2,
        likes_count: 15,
        creation_date: new Date("2026-10-02T14:27:00"),
        refreshToken: "",
      },
      {
        id: 73,
        bio: "Люблю спорт, путешествия и хорошие документальные фильмы.",
        email: "maxim2@mail.ru",
        password: "12345",
        name: "Максим",
        image_path: "avatar-73.jpg",
        gender_id: 1,
        birth_date: new Date("1998-08-18"),
        city_id: 6,
        likes_count: 20,
        creation_date: new Date("2026-10-03T08:44:00"),
        refreshToken: "",
      },
      {
        id: 74,
        bio: "Учу французский и собираю рецепты французской кухни.",
        email: "daria2@mail.ru",
        password: "12345",
        name: "Дарья",
        image_path: "avatar-74.jpg",
        gender_id: 2,
        birth_date: new Date("2002-06-25"),
        city_id: 1,
        likes_count: 9,
        creation_date: new Date("2026-10-03T12:16:00"),
        refreshToken: "",
      },
      {
        id: 75,
        bio: "Интересуюсь предпринимательством и постоянно записываю новые идеи.",
        email: "andrey2@mail.ru",
        password: "12345",
        name: "Андрей",
        image_path: "avatar-75.jpg",
        gender_id: 1,
        birth_date: new Date("1994-10-07"),
        city_id: 4,
        likes_count: 23,
        creation_date: new Date("2026-10-03T17:39:00"),
        refreshToken: "",
      },
      {
        id: 76,
        bio: "Люблю танцевать, путешествовать и пробовать новые хобби.",
        email: "olga2@mail.ru",
        password: "12345",
        name: "Ольга",
        image_path: "avatar-76.jpg",
        gender_id: 2,
        birth_date: new Date("1997-02-28"),
        city_id: 7,
        likes_count: 18,
        creation_date: new Date("2026-10-04T09:53:00"),
        refreshToken: "",
      },
      {
        id: 77,
        bio: "Фотографирую природу и учусь работать со светом.",
        email: "petr@mail.ru",
        password: "12345",
        name: "Пётр",
        image_path: "avatar-77.jpg",
        gender_id: 1,
        birth_date: new Date("1996-05-11"),
        city_id: 3,
        likes_count: 6,
        creation_date: new Date("2026-10-04T11:28:00"),
        refreshToken: "",
      },
      {
        id: 78,
        bio: "Изучаю дизайн и люблю превращать сложные идеи в простые интерфейсы.",
        email: "anna2@mail.ru",
        password: "12345",
        name: "Анна",
        image_path: "avatar-78.jpg",
        gender_id: 2,
        birth_date: new Date("2000-08-14"),
        city_id: 5,
        likes_count: 26,
        creation_date: new Date("2026-10-04T15:42:00"),
        refreshToken: "",
      },
      {
        id: 79,
        bio: "Играю в шахматы и изучаю английский через разговорную практику.",
        email: "alexey2@mail.ru",
        password: "12345",
        name: "Алексей",
        image_path: "avatar-79.jpg",
        gender_id: 1,
        birth_date: new Date("2001-01-22"),
        city_id: 2,
        likes_count: 13,
        creation_date: new Date("2026-10-05T08:17:00"),
        refreshToken: "",
      },
      {
        id: 80,
        bio: "Люблю книги, театр и долгие разговоры о жизни.",
        email: "polina2@mail.ru",
        password: "12345",
        name: "Полина",
        image_path: "avatar-80.jpg",
        gender_id: 2,
        birth_date: new Date("1998-09-30"),
        city_id: 6,
        likes_count: 10,
        creation_date: new Date("2026-10-05T10:36:00"),
        refreshToken: "",
      },
      {
        id: 81,
        bio: "Занимаюсь спортом и интересуюсь правильным восстановлением.",
        email: "vladimir@mail.ru",
        password: "12345",
        name: "Владимир",
        image_path: "avatar-81.jpg",
        gender_id: 1,
        birth_date: new Date("1993-12-16"),
        city_id: 1,
        likes_count: 16,
        creation_date: new Date("2026-10-05T12:54:00"),
        refreshToken: "",
      },
      {
        id: 82,
        bio: "Учу испанский и мечтаю проехать всю Испанию на машине.",
        email: "veronika2@mail.ru",
        password: "12345",
        name: "Вероника",
        image_path: "avatar-82.jpg",
        gender_id: 2,
        birth_date: new Date("2003-07-04"),
        city_id: 4,
        likes_count: 21,
        creation_date: new Date("2026-10-05T14:19:00"),
        refreshToken: "",
      },
      {
        id: 83,
        bio: "Пишу музыку и учусь не бояться показывать свои работы другим.",
        email: "roman3@mail.ru",
        password: "12345",
        name: "Роман",
        image_path: "avatar-83.jpg",
        gender_id: 1,
        birth_date: new Date("1997-04-13"),
        city_id: 7,
        likes_count: 8,
        creation_date: new Date("2026-10-05T16:31:00"),
        refreshToken: "",
      },
      {
        id: 84,
        bio: "Обожаю керамику, рукоделие и всё, что можно сделать своими руками.",
        email: "alina2@mail.ru",
        password: "12345",
        name: "Алина",
        image_path: "avatar-84.jpg",
        gender_id: 2,
        birth_date: new Date("1999-11-05"),
        city_id: 3,
        likes_count: 17,
        creation_date: new Date("2026-10-05T18:04:00"),
        refreshToken: "",
      },
      {
        id: 85,
        bio: "Интересуюсь историей, языками и путешествиями.",
        email: "dmitry2@mail.ru",
        password: "12345",
        name: "Дмитрий",
        image_path: "avatar-85.jpg",
        gender_id: 1,
        birth_date: new Date("1995-06-22"),
        city_id: 5,
        likes_count: 14,
        creation_date: new Date("2026-10-06T08:12:00"),
        refreshToken: "",
      },
      {
        id: 86,
        bio: "Учу английский и люблю помогать людям перестать бояться говорить.",
        email: "marina2@mail.ru",
        password: "12345",
        name: "Марина",
        image_path: "avatar-86.jpg",
        gender_id: 2,
        birth_date: new Date("1996-02-09"),
        city_id: 2,
        likes_count: 24,
        creation_date: new Date("2026-10-06T09:27:00"),
        refreshToken: "",
      },
      {
        id: 87,
        bio: "Люблю велосипеды, кофе и ранние поездки за город.",
        email: "konstantin@mail.ru",
        password: "12345",
        name: "Константин",
        image_path: "avatar-87.jpg",
        gender_id: 1,
        birth_date: new Date("1992-08-26"),
        city_id: 6,
        likes_count: 5,
        creation_date: new Date("2026-10-06T10:43:00"),
        refreshToken: "",
      },
      {
        id: 88,
        bio: "Занимаюсь иллюстрацией и учусь работать в новых графических редакторах.",
        email: "yulia2@mail.ru",
        password: "12345",
        name: "Юлия",
        image_path: "avatar-88.jpg",
        gender_id: 2,
        birth_date: new Date("2001-10-15"),
        city_id: 1,
        likes_count: 18,
        creation_date: new Date("2026-10-06T11:18:00"),
        refreshToken: "",
      },
      {
        id: 89,
        bio: "Разрабатываю сайты и хочу лучше разбираться в архитектуре приложений.",
        email: "igor2@mail.ru",
        password: "12345",
        name: "Игорь",
        image_path: "avatar-89.jpg",
        gender_id: 1,
        birth_date: new Date("1998-01-07"),
        city_id: 4,
        likes_count: 12,
        creation_date: new Date("2026-10-06T12:06:00"),
        refreshToken: "",
      },
      {
        id: 90,
        bio: "Люблю йогу, плавание и спокойные путешествия.",
        email: "kristina@mail.ru",
        password: "12345",
        name: "Кристина",
        image_path: "avatar-90.jpg",
        gender_id: 2,
        birth_date: new Date("1997-05-29"),
        city_id: 7,
        likes_count: 20,
        creation_date: new Date("2026-10-06T13:14:00"),
        refreshToken: "",
      },
      {
        id: 91,
        bio: "Учу людей работать с фотографией и сам постоянно совершенствуюсь.",
        email: "alexander2@mail.ru",
        password: "12345",
        name: "Александр",
        image_path: "avatar-91.jpg",
        gender_id: 1,
        birth_date: new Date("1994-03-18"),
        city_id: 3,
        likes_count: 9,
        creation_date: new Date("2026-10-06T14:02:00"),
        refreshToken: "",
      },
      {
        id: 92,
        bio: "Интересуюсь психологией, коммуникацией и изучением языков.",
        email: "oksana2@mail.ru",
        password: "12345",
        name: "Оксана",
        image_path: "avatar-92.jpg",
        gender_id: 2,
        birth_date: new Date("2000-12-27"),
        city_id: 5,
        likes_count: 23,
        creation_date: new Date("2026-10-06T14:46:00"),
        refreshToken: "",
      },
      {
        id: 93,
        bio: "Программирую, играю в настольные игры и люблю технические задачи.",
        email: "vadim2@mail.ru",
        password: "12345",
        name: "Вадим",
        image_path: "avatar-93.jpg",
        gender_id: 1,
        birth_date: new Date("1999-09-02"),
        city_id: 2,
        likes_count: 15,
        creation_date: new Date("2026-10-06T15:21:00"),
        refreshToken: "",
      },
      {
        id: 94,
        bio: "Люблю печь десерты и экспериментировать с новыми рецептами.",
        email: "valeria2@mail.ru",
        password: "12345",
        name: "Валерия",
        image_path: "avatar-94.jpg",
        gender_id: 2,
        birth_date: new Date("2002-04-11"),
        city_id: 6,
        likes_count: 19,
        creation_date: new Date("2026-10-06T16:03:00"),
        refreshToken: "",
      },
      {
        id: 95,
        bio: "Изучаю менеджмент и пытаюсь научиться хорошо планировать время.",
        email: "evgeny2@mail.ru",
        password: "12345",
        name: "Евгений",
        image_path: "avatar-95.jpg",
        gender_id: 1,
        birth_date: new Date("1996-07-24"),
        city_id: 1,
        likes_count: 7,
        creation_date: new Date("2026-10-06T16:38:00"),
        refreshToken: "",
      },
      {
        id: 96,
        bio: "Учу итальянский, фотографирую еду и мечтаю о маленьком кафе.",
        email: "diana2@mail.ru",
        password: "12345",
        name: "Диана",
        image_path: "avatar-96.jpg",
        gender_id: 2,
        birth_date: new Date("2003-02-28"),
        city_id: 4,
        likes_count: 26,
        creation_date: new Date("2026-10-06T17:11:00"),
        refreshToken: "",
      },
      {
        id: 97,
        bio: "Люблю бег, музыку и разговоры о технологиях.",
        email: "sergey3@mail.ru",
        password: "12345",
        name: "Сергей",
        image_path: "avatar-97.jpg",
        gender_id: 1,
        birth_date: new Date("1995-11-19"),
        city_id: 7,
        likes_count: 10,
        creation_date: new Date("2026-10-06T18:24:00"),
        refreshToken: "",
      },
      {
        id: 98,
        bio: "Изучаю дизайн и собираю портфолио из реальных учебных проектов.",
        email: "maria3@mail.ru",
        password: "12345",
        name: "Мария",
        image_path: "avatar-98.jpg",
        gender_id: 2,
        birth_date: new Date("2001-06-06"),
        city_id: 3,
        likes_count: 17,
        creation_date: new Date("2026-10-06T19:05:00"),
        refreshToken: "",
      },
      {
        id: 99,
        bio: "Интересуюсь предпринимательством, маркетингом и развитием продуктов.",
        email: "pavel2@mail.ru",
        password: "12345",
        name: "Павел",
        image_path: "avatar-99.jpg",
        gender_id: 1,
        birth_date: new Date("1993-10-21"),
        city_id: 5,
        likes_count: 22,
        creation_date: new Date("2026-10-06T20:17:00"),
        refreshToken: "",
      },
      {
        id: 100,
        bio: "Люблю языки, книги и новые знакомства. Всегда рада чему-то научиться.",
        email: "anna3@mail.ru",
        password: "12345",
        name: "Анна",
        image_path: "avatar-100.jpg",
        gender_id: 2,
        birth_date: new Date("2004-03-15"),
        city_id: 2,
        likes_count: 29,
        creation_date: new Date("2026-10-06T21:32:00"),
        refreshToken: "",
      },
    ],
  });
  console.log("Creating user_can_teach data...");
  await prisma.userCanTeach.createMany({
    data: [
      {
        title: "Музыка и звук",
        user_id: 1,
        subskill_id: 12,
      },
      {
        title: "Английский",
        user_id: 2,
        subskill_id: 23,
      },
      {
        title: "Личный бренд",
        user_id: 3,
        subskill_id: 4,
      },
      {
        title: "Английский",
        user_id: 4,
        subskill_id: 23,
      },
      {
        title: "Английский",
        user_id: 5,
        subskill_id: 23,
      },
      {
        title: "Музыка и звук",
        user_id: 6,
        subskill_id: 12,
      },
      {
        title: "Фотография",
        user_id: 7,
        subskill_id: 10,
      },
      {
        title: "Приготовление еды",
        user_id: 8,
        subskill_id: 39,
      },
      {
        title: "Личностное развитие",
        user_id: 9,
        subskill_id: 17,
      },
      {
        title: "Испанский",
        user_id: 10,
        subskill_id: 25,
      },
      {
        title: "Когнитивные техники",
        user_id: 11,
        subskill_id: 19,
      },
      {
        title: "Рисование и иллюстрация",
        user_id: 12,
        subskill_id: 9,
      },
      {
        title: "Йога и медитация",
        user_id: 13,
        subskill_id: 30,
      },
      {
        title: "Музыка и звук",
        user_id: 14,
        subskill_id: 12,
      },
      {
        title: "Видеомонтаж",
        user_id: 15,
        subskill_id: 11,
      },
      {
        title: "Немецкий",
        user_id: 16,
        subskill_id: 26,
      },
      {
        title: "Продажи и переговоры",
        user_id: 17,
        subskill_id: 3,
      },
      {
        title: "Физические тренировки",
        user_id: 18,
        subskill_id: 34,
      },
      {
        title: "Маркетинг и реклама",
        user_id: 19,
        subskill_id: 2,
      },
      {
        title: "Рисование и иллюстрация",
        user_id: 20,
        subskill_id: 9,
      },
      {
        title: "Фотография",
        user_id: 21,
        subskill_id: 10,
      },
      {
        title: "Французский",
        user_id: 22,
        subskill_id: 24,
      },
      {
        title: "Домашние финансы",
        user_id: 23,
        subskill_id: 38,
      },
      {
        title: "Личностное развитие",
        user_id: 24,
        subskill_id: 17,
      },
      {
        title: "Приготовление еды",
        user_id: 25,
        subskill_id: 39,
      },
      {
        title: "Актерское мастерство",
        user_id: 26,
        subskill_id: 13,
      },
      {
        title: "Личностное развитие",
        user_id: 27,
        subskill_id: 17,
      },
      {
        title: "Ментальное здоровье",
        user_id: 28,
        subskill_id: 32,
      },
      {
        title: "Видеомонтаж",
        user_id: 29,
        subskill_id: 11,
      },
      {
        title: "Рисование и иллюстрация",
        user_id: 30,
        subskill_id: 9,
      },
      {
        title: "Физические тренировки",
        user_id: 31,
        subskill_id: 34,
      },
      {
        title: "Музыка и звук",
        user_id: 32,
        subskill_id: 12,
      },
      {
        title: "Декор и DIY",
        user_id: 33,
        subskill_id: 16,
      },
      {
        title: "Рисование и иллюстрация",
        user_id: 34,
        subskill_id: 9,
      },
      {
        title: "Физические тренировки",
        user_id: 35,
        subskill_id: 34,
      },
      {
        title: "Французский",
        user_id: 36,
        subskill_id: 24,
      },
      {
        title: "Когнитивные техники",
        user_id: 37,
        subskill_id: 19,
      },
      {
        title: "Фотография",
        user_id: 38,
        subskill_id: 10,
      },
      {
        title: "Когнитивные техники",
        user_id: 39,
        subskill_id: 19,
      },
      {
        title: "Креативное письмо",
        user_id: 40,
        subskill_id: 14,
      },
      {
        title: "Личностное развитие",
        user_id: 41,
        subskill_id: 17,
      },
      {
        title: "Домашние растения",
        user_id: 42,
        subskill_id: 40,
      },
      {
        title: "Ремонт",
        user_id: 43,
        subskill_id: 41,
      },
      {
        title: "Японский",
        user_id: 44,
        subskill_id: 28,
      },
      {
        title: "Физические тренировки",
        user_id: 45,
        subskill_id: 34,
      },
      {
        title: "Музыка и звук",
        user_id: 46,
        subskill_id: 12,
      },
      {
        title: "Маркетинг и реклама",
        user_id: 47,
        subskill_id: 2,
      },
      {
        title: "Испанский",
        user_id: 48,
        subskill_id: 25,
      },
      {
        title: "Когнитивные техники",
        user_id: 49,
        subskill_id: 19,
      },
      {
        title: "Музыка и звук",
        user_id: 50,
        subskill_id: 12,
      },
      {
        title: "Личностное развитие",
        user_id: 51,
        subskill_id: 17,
      },
      {
        title: "Рисование и иллюстрация",
        user_id: 52,
        subskill_id: 9,
      },
      {
        title: "Личностное развитие",
        user_id: 53,
        subskill_id: 17,
      },
      {
        title: "Японский",
        user_id: 54,
        subskill_id: 28,
      },
      {
        title: "Физические тренировки",
        user_id: 55,
        subskill_id: 34,
      },
      {
        title: "Приготовление еды",
        user_id: 56,
        subskill_id: 39,
      },
      {
        title: "Когнитивные техники",
        user_id: 57,
        subskill_id: 19,
      },
      {
        title: "Английский",
        user_id: 58,
        subskill_id: 23,
      },
      {
        title: "Фотография",
        user_id: 59,
        subskill_id: 10,
      },
      {
        title: "Продажи и переговоры",
        user_id: 60,
        subskill_id: 3,
      },
      {
        title: "Физические тренировки",
        user_id: 61,
        subskill_id: 34,
      },
      {
        title: "Музыка и звук",
        user_id: 62,
        subskill_id: 12,
      },
      {
        title: "Когнитивные техники",
        user_id: 63,
        subskill_id: 19,
      },
      {
        title: "Йога и медитация",
        user_id: 64,
        subskill_id: 30,
      },
      {
        title: "Личностное развитие",
        user_id: 65,
        subskill_id: 17,
      },
      {
        title: "Креативное письмо",
        user_id: 66,
        subskill_id: 14,
      },
      {
        title: "Приготовление еды",
        user_id: 67,
        subskill_id: 39,
      },
      {
        title: "Немецкий",
        user_id: 68,
        subskill_id: 26,
      },
      {
        title: "Музыка и звук",
        user_id: 69,
        subskill_id: 12,
      },
      {
        title: "Личностное развитие",
        user_id: 70,
        subskill_id: 17,
      },
      {
        title: "Личностное развитие",
        user_id: 71,
        subskill_id: 17,
      },
      {
        title: "Рисование и иллюстрация",
        user_id: 72,
        subskill_id: 9,
      },
      {
        title: "Физические тренировки",
        user_id: 73,
        subskill_id: 34,
      },
      {
        title: "Французский",
        user_id: 74,
        subskill_id: 24,
      },
      {
        title: "Предпринимательство",
        user_id: 75,
        subskill_id: 8,
      },
      {
        title: "Актерское мастерство",
        user_id: 76,
        subskill_id: 13,
      },
      {
        title: "Фотография",
        user_id: 77,
        subskill_id: 10,
      },
      {
        title: "Продажи и переговоры",
        user_id: 78,
        subskill_id: 3,
      },
      {
        title: "Когнитивные техники",
        user_id: 79,
        subskill_id: 19,
      },
      {
        title: "Креативное письмо",
        user_id: 80,
        subskill_id: 14,
      },
      {
        title: "Физические тренировки",
        user_id: 81,
        subskill_id: 34,
      },
      {
        title: "Испанский",
        user_id: 82,
        subskill_id: 25,
      },
      {
        title: "Музыка и звук",
        user_id: 83,
        subskill_id: 12,
      },
      {
        title: "Декор и DIY",
        user_id: 84,
        subskill_id: 16,
      },
      {
        title: "Личностное развитие",
        user_id: 85,
        subskill_id: 17,
      },
      {
        title: "Английский",
        user_id: 86,
        subskill_id: 23,
      },
      {
        title: "Физические тренировки",
        user_id: 87,
        subskill_id: 34,
      },
      {
        title: "Рисование и иллюстрация",
        user_id: 88,
        subskill_id: 9,
      },
      {
        title: "Личностное развитие",
        user_id: 89,
        subskill_id: 17,
      },
      {
        title: "Йога и медитация",
        user_id: 90,
        subskill_id: 30,
      },
      {
        title: "Фотография",
        user_id: 91,
        subskill_id: 10,
      },
      {
        title: "Ментальное здоровье",
        user_id: 92,
        subskill_id: 32,
      },
      {
        title: "Личностное развитие",
        user_id: 93,
        subskill_id: 17,
      },
      {
        title: "Приготовление еды",
        user_id: 94,
        subskill_id: 39,
      },
      {
        title: "Управление командой",
        user_id: 95,
        subskill_id: 1,
      },
      {
        title: "Французский",
        user_id: 96,
        subskill_id: 24,
      },
      {
        title: "Физические тренировки",
        user_id: 97,
        subskill_id: 34,
      },
      {
        title: "Продажи и переговоры",
        user_id: 98,
        subskill_id: 3,
      },
      {
        title: "Маркетинг и реклама",
        user_id: 99,
        subskill_id: 2,
      },
      {
        title: "Английский",
        user_id: 100,
        subskill_id: 23,
      },
    ],
  });
  console.log("Creating user_wants_to_learn data...");
  await prisma.userWantsToLearn.createMany({
    data: [
      { title: "Тайм-менеджмент", user_id: 1, subskill_id: 6 },
      { title: "Йога и медитация", user_id: 1, subskill_id: 30 },
      { title: "Французский", user_id: 2, subskill_id: 24 },
      { title: "Китайский", user_id: 2, subskill_id: 27 },
      { title: "Тайм-менеджмент", user_id: 3, subskill_id: 6 },
      { title: "Французский", user_id: 3, subskill_id: 24 },
      { title: "Йога и медитация", user_id: 4, subskill_id: 30 },
      { title: "Китайский", user_id: 4, subskill_id: 27 },
      { title: "Тайм-менеджмент", user_id: 5, subskill_id: 6 },
      { title: "Китайский", user_id: 5, subskill_id: 27 },
      { title: "Французский", user_id: 6, subskill_id: 24 },
      { title: "Йога и медитация", user_id: 6, subskill_id: 30 },
      { title: "Тайм-менеджмент", user_id: 7, subskill_id: 6 },
      { title: "Французский", user_id: 7, subskill_id: 24 },
      { title: "Йога и медитация", user_id: 8, subskill_id: 30 },
      { title: "Китайский", user_id: 8, subskill_id: 27 },
      { title: "Французский", user_id: 9, subskill_id: 24 },
      { title: "Тайм-менеджмент", user_id: 9, subskill_id: 6 },
      { title: "Китайский", user_id: 10, subskill_id: 27 },
      { title: "Йога и медитация", user_id: 10, subskill_id: 30 },
      { title: "Тайм-менеджмент", user_id: 11, subskill_id: 6 },
      { title: "Китайский", user_id: 11, subskill_id: 27 },
      { title: "Французский", user_id: 12, subskill_id: 24 },
      { title: "Йога и медитация", user_id: 12, subskill_id: 30 },
      { title: "Тайм-менеджмент", user_id: 13, subskill_id: 6 },
      { title: "Французский", user_id: 13, subskill_id: 24 },
      { title: "Йога и медитация", user_id: 14, subskill_id: 30 },
      { title: "Китайский", user_id: 14, subskill_id: 27 },
      { title: "Тайм-менеджмент", user_id: 15, subskill_id: 6 },
      { title: "Китайский", user_id: 15, subskill_id: 27 },
      { title: "Французский", user_id: 16, subskill_id: 24 },
      { title: "Йога и медитация", user_id: 16, subskill_id: 30 },
      { title: "Тайм-менеджмент", user_id: 17, subskill_id: 6 },
      { title: "Французский", user_id: 17, subskill_id: 24 },
      { title: "Йога и медитация", user_id: 18, subskill_id: 30 },
      { title: "Китайский", user_id: 18, subskill_id: 27 },
      { title: "Тайм-менеджмент", user_id: 19, subskill_id: 6 },
      { title: "Китайский", user_id: 19, subskill_id: 27 },
      { title: "Французский", user_id: 20, subskill_id: 24 },
      { title: "Йога и медитация", user_id: 20, subskill_id: 30 },
      { title: "Тайм-менеджмент", user_id: 21, subskill_id: 6 },
      { title: "Английский", user_id: 21, subskill_id: 23 },
      { title: "Йога и медитация", user_id: 22, subskill_id: 30 },
      { title: "Китайский", user_id: 22, subskill_id: 27 },
      { title: "Тайм-менеджмент", user_id: 23, subskill_id: 6 },
      { title: "Английский", user_id: 23, subskill_id: 23 },
      { title: "Французский", user_id: 24, subskill_id: 24 },
      { title: "Йога и медитация", user_id: 24, subskill_id: 30 },
      { title: "Английский", user_id: 25, subskill_id: 23 },
      { title: "Фотография", user_id: 25, subskill_id: 10 },
      { title: "Музыка и звук", user_id: 26, subskill_id: 12 },
      { title: "Испанский", user_id: 26, subskill_id: 25 },
      { title: "Тайм-менеджмент", user_id: 27, subskill_id: 6 },
      { title: "Баланс жизни и работы", user_id: 27, subskill_id: 36 },
      { title: "Коучинг", user_id: 28, subskill_id: 22 },
      { title: "Осознанность", user_id: 28, subskill_id: 33 },
      { title: "Музыка и звук", user_id: 29, subskill_id: 12 },
      { title: "Креативное письмо", user_id: 29, subskill_id: 14 },
      { title: "Фотография", user_id: 30, subskill_id: 10 },
      { title: "Арт-терапия", user_id: 30, subskill_id: 15 },
      { title: "Питание и ЗОЖ", user_id: 31, subskill_id: 31 },
      { title: "Сон и восстановление", user_id: 31, subskill_id: 35 },
      { title: "Актерское мастерство", user_id: 32, subskill_id: 13 },
      { title: "Английский", user_id: 32, subskill_id: 23 },
      { title: "Ремонт", user_id: 33, subskill_id: 41 },
      { title: "Хранение вещей", user_id: 33, subskill_id: 42 },
      { title: "Маркетинг и реклама", user_id: 34, subskill_id: 2 },
      { title: "Личный бренд", user_id: 34, subskill_id: 4 },
      { title: "Осознанность", user_id: 35, subskill_id: 33 },
      { title: "Йога и медитация", user_id: 35, subskill_id: 30 },
      { title: "Приготовление еды", user_id: 36, subskill_id: 39 },
      { title: "Фотография", user_id: 36, subskill_id: 10 },
      { title: "Тайм-менеджмент", user_id: 37, subskill_id: 6 },
      { title: "Навыки обучения", user_id: 37, subskill_id: 18 },
      { title: "Креативное письмо", user_id: 38, subskill_id: 14 },
      { title: "Видеомонтаж", user_id: 38, subskill_id: 11 },
      { title: "Тайм-менеджмент", user_id: 39, subskill_id: 6 },
      { title: "Английский", user_id: 39, subskill_id: 23 },
      { title: "Скорочтение", user_id: 40, subskill_id: 20 },
      { title: "Навыки обучения", user_id: 40, subskill_id: 18 },
      { title: "Маркетинг и реклама", user_id: 41, subskill_id: 2 },
      { title: "Проектное управление", user_id: 41, subskill_id: 7 },
      { title: "Уборка и организация", user_id: 42, subskill_id: 37 },
      { title: "Декор и DIY", user_id: 42, subskill_id: 16 },
      { title: "Проектное управление", user_id: 43, subskill_id: 7 },
      { title: "Тайм-менеджмент", user_id: 43, subskill_id: 6 },
      { title: "Китайский", user_id: 44, subskill_id: 27 },
      { title: "Английский", user_id: 44, subskill_id: 23 },
      { title: "Тайм-менеджмент", user_id: 45, subskill_id: 6 },
      { title: "Сон и восстановление", user_id: 45, subskill_id: 35 },
      { title: "Йога и медитация", user_id: 46, subskill_id: 30 },
      { title: "Фотография", user_id: 46, subskill_id: 10 },
      { title: "Когнитивные техники", user_id: 47, subskill_id: 19 },
      { title: "Тайм-менеджмент", user_id: 47, subskill_id: 6 },
      { title: "Французский", user_id: 48, subskill_id: 24 },
      { title: "Йога и медитация", user_id: 48, subskill_id: 30 },
      { title: "Когнитивные техники", user_id: 49, subskill_id: 19 },
      { title: "Личностное развитие", user_id: 49, subskill_id: 17 },
      { title: "Актерское мастерство", user_id: 50, subskill_id: 13 },
      { title: "Английский", user_id: 50, subskill_id: 23 },
      { title: "Фотография", user_id: 51, subskill_id: 10 },
      { title: "Английский", user_id: 51, subskill_id: 23 },
      { title: "Видеомонтаж", user_id: 52, subskill_id: 11 },
      { title: "Арт-терапия", user_id: 52, subskill_id: 15 },
      { title: "Скорочтение", user_id: 53, subskill_id: 20 },
      { title: "Креативное письмо", user_id: 53, subskill_id: 14 },
      { title: "Китайский", user_id: 54, subskill_id: 27 },
      { title: "Английский", user_id: 54, subskill_id: 23 },
      { title: "Питание и ЗОЖ", user_id: 55, subskill_id: 31 },
      { title: "Сон и восстановление", user_id: 55, subskill_id: 35 },
      { title: "Фотография", user_id: 56, subskill_id: 10 },
      { title: "Домашние финансы", user_id: 56, subskill_id: 38 },
      { title: "Тайм-менеджмент", user_id: 57, subskill_id: 6 },
      { title: "Навыки обучения", user_id: 57, subskill_id: 18 },
      { title: "Испанский", user_id: 58, subskill_id: 25 },
      { title: "Йога и медитация", user_id: 58, subskill_id: 30 },
      { title: "Видеомонтаж", user_id: 59, subskill_id: 11 },
      { title: "Креативное письмо", user_id: 59, subskill_id: 14 },
      { title: "Маркетинг и реклама", user_id: 60, subskill_id: 2 },
      { title: "Личный бренд", user_id: 60, subskill_id: 4 },
      { title: "Питание и ЗОЖ", user_id: 61, subskill_id: 31 },
      { title: "Осознанность", user_id: 61, subskill_id: 33 },
      { title: "Актерское мастерство", user_id: 62, subskill_id: 13 },
      { title: "Французский", user_id: 62, subskill_id: 24 },
      { title: "Английский", user_id: 63, subskill_id: 23 },
      { title: "Навыки обучения", user_id: 63, subskill_id: 18 },
      { title: "Сон и восстановление", user_id: 64, subskill_id: 35 },
      { title: "Осознанность", user_id: 64, subskill_id: 33 },
      { title: "Тайм-менеджмент", user_id: 65, subskill_id: 6 },
      { title: "Проектное управление", user_id: 65, subskill_id: 7 },
      { title: "Фотография", user_id: 66, subskill_id: 10 },
      { title: "Арт-терапия", user_id: 66, subskill_id: 15 },
      { title: "Домашние финансы", user_id: 67, subskill_id: 38 },
      { title: "Уборка и организация", user_id: 67, subskill_id: 37 },
      { title: "Английский", user_id: 68, subskill_id: 23 },
      { title: "Тайм-менеджмент", user_id: 68, subskill_id: 6 },
      { title: "Видеомонтаж", user_id: 69, subskill_id: 11 },
      { title: "Креативное письмо", user_id: 69, subskill_id: 14 },
      { title: "Английский", user_id: 70, subskill_id: 23 },
      { title: "Фотография", user_id: 70, subskill_id: 10 },
      { title: "Тайм-менеджмент", user_id: 71, subskill_id: 6 },
      { title: "Навыки обучения", user_id: 71, subskill_id: 18 },
      { title: "Скорочтение", user_id: 72, subskill_id: 20 },
      { title: "Арт-терапия", user_id: 72, subskill_id: 15 },
      { title: "Питание и ЗОЖ", user_id: 73, subskill_id: 31 },
      { title: "Сон и восстановление", user_id: 73, subskill_id: 35 },
      { title: "Приготовление еды", user_id: 74, subskill_id: 39 },
      { title: "Фотография", user_id: 74, subskill_id: 10 },
      { title: "Маркетинг и реклама", user_id: 75, subskill_id: 2 },
      { title: "Личный бренд", user_id: 75, subskill_id: 4 },
      { title: "Испанский", user_id: 76, subskill_id: 25 },
      { title: "Фотография", user_id: 76, subskill_id: 10 },
      { title: "Видеомонтаж", user_id: 77, subskill_id: 11 },
      { title: "Декор и DIY", user_id: 77, subskill_id: 16 },
      { title: "Маркетинг и реклама", user_id: 78, subskill_id: 2 },
      { title: "Личный бренд", user_id: 78, subskill_id: 4 },
      { title: "Английский", user_id: 79, subskill_id: 23 },
      { title: "Тайм-менеджмент", user_id: 79, subskill_id: 6 },
      { title: "Актерское мастерство", user_id: 80, subskill_id: 13 },
      { title: "Креативное письмо", user_id: 80, subskill_id: 14 },
      { title: "Сон и восстановление", user_id: 81, subskill_id: 35 },
      { title: "Питание и ЗОЖ", user_id: 81, subskill_id: 31 },
      { title: "Французский", user_id: 82, subskill_id: 24 },
      { title: "Йога и медитация", user_id: 82, subskill_id: 30 },
      { title: "Актерское мастерство", user_id: 83, subskill_id: 13 },
      { title: "Видеомонтаж", user_id: 83, subskill_id: 11 },
      { title: "Домашние растения", user_id: 84, subskill_id: 40 },
      { title: "Уборка и организация", user_id: 84, subskill_id: 37 },
      { title: "Английский", user_id: 85, subskill_id: 23 },
      { title: "Скорочтение", user_id: 85, subskill_id: 20 },
      { title: "Коучинг", user_id: 86, subskill_id: 22 },
      { title: "Навыки преподавания", user_id: 86, subskill_id: 21 },
      { title: "Питание и ЗОЖ", user_id: 87, subskill_id: 31 },
      { title: "Осознанность", user_id: 87, subskill_id: 33 },
      { title: "Фотография", user_id: 88, subskill_id: 10 },
      { title: "Арт-терапия", user_id: 88, subskill_id: 15 },
      { title: "Проектное управление", user_id: 89, subskill_id: 7 },
      { title: "Тайм-менеджмент", user_id: 89, subskill_id: 6 },
      { title: "Физические тренировки", user_id: 90, subskill_id: 34 },
      { title: "Сон и восстановление", user_id: 90, subskill_id: 35 },
      { title: "Видеомонтаж", user_id: 91, subskill_id: 11 },
      { title: "Маркетинг и реклама", user_id: 91, subskill_id: 2 },
      { title: "Английский", user_id: 92, subskill_id: 23 },
      { title: "Коучинг", user_id: 92, subskill_id: 22 },
      { title: "Когнитивные техники", user_id: 93, subskill_id: 19 },
      { title: "Тайм-менеджмент", user_id: 93, subskill_id: 6 },
      { title: "Фотография", user_id: 94, subskill_id: 10 },
      { title: "Домашние финансы", user_id: 94, subskill_id: 38 },
      { title: "Тайм-менеджмент", user_id: 95, subskill_id: 6 },
      { title: "Проектное управление", user_id: 95, subskill_id: 7 },
      { title: "Приготовление еды", user_id: 96, subskill_id: 39 },
      { title: "Фотография", user_id: 96, subskill_id: 10 },
      { title: "Музыка и звук", user_id: 97, subskill_id: 12 },
      { title: "Тайм-менеджмент", user_id: 97, subskill_id: 6 },
      { title: "Маркетинг и реклама", user_id: 98, subskill_id: 2 },
      { title: "Личный бренд", user_id: 98, subskill_id: 4 },
      { title: "Личный бренд", user_id: 99, subskill_id: 4 },
      { title: "Проектное управление", user_id: 99, subskill_id: 7 },
      { title: "Китайский", user_id: 100, subskill_id: 27 },
      { title: "Японский", user_id: 100, subskill_id: 28 },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
    await pool.end();
    process.exit(0);
  })
  .catch(async (e) => {
    console.log(e);
    await prisma.$disconnect();
    await pool.end();
    process.exit(1);
  });
